@hostname = localhost
@port = 4000
@personId = 1
@path = slides/id
@host = http://{{hostname}}:{{port}}

###

GET {{host}}/config/ HTTP/1.1
Accept: application/json

###


GET {{host}}/config/{{path}} HTTP/1.1
Accept: application/json

###

POST {{host}}/config HTTP/1.1
Accept: application/json
Content-Type: application/json

[
    {
        "id": 0,
        "name": "vvvd",
        "group": "",
        "picture": "",
        "domainId": -1,
        "domainOrder": -1
    },
    {
        "id": 1,
        "name": "vvvd",
        "group": "",
        "picture": "",
        "domainId": -1,
        "domainOrder": -1
    }
]