@hostname = localhost
@port = 4000
@personId = 1
@path = slides/id
@host = http://{{hostname}}:{{port}}

###

GET {{host}}/api/pictures/1d4a1ce4-6b59-4970-b419-5d9b9bbe2beb HTTP/1.1
Accept: application/json